discord:
  - id: "manualcheck"
    discord_channel: "manualcheck"
    discord_username: "manualcheck"
    discord_format: "{{data}}"
    discord_webhook_url: ""

  - id: "subdomain"
    discord_channel: "subdomain"
    discord_username: "subdomain"
    discord_format: "{{data}}"
    discord_webhook_url: ""

  - id: "ports"
    discord_channel: "ports"
    discord_username: "ports"
    discord_format: "{{data}}"
    discord_webhook_url: ""

  - id: "alivesubdomain"
    discord_channel: "alivesubdomain"
    discord_username: "alivesubdomain"
    discord_format: "{{data}}"
    discord_webhook_url: ""

  - id: "javascript"
    discord_channel: "javascript"
    discord_username: "javascript"
    discord_format: "{{data}}"
    discord_webhook_url: ""

  - id: "javascriptleaks"
    discord_channel: "javascriptleaks"
    discord_username: "javascriptleaks"
    discord_format: "{{data}}"
    discord_webhook_url: ""

  - id: "xss"
    discord_channel: "xss"
    discord_username: "xss"
    discord_format: "{{data}}"
    discord_webhook_url: ""

  - id: "allvuln"
    discord_channel: "allvuln"
    discord_username: "allvuln"
    discord_format: "{{data}}"
    discord_webhook_url: ""

  - id: "scanfinished"
    discord_channel: "scanfinished"
    discord_username: "scanfinished"
    discord_format: "{{data}}"
    discord_webhook_url: ""